name: Continuous integration

on:
  pull_request:

env:
  MODULE_DEPLOYMENT_DIR: "module-deployment"

jobs:
  tfsec-pr-commenter:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          working_directory: ${{ env.MODULE_DEPLOYMENT_DIR }}
